### ISSUE TITLE
Missing dependency in farmOS 7.x-1.3

### ISSUE THREAD

**Issue by botlfarm** [farmOS/farm_bee#2]
I tried an update today to farmOS 7.x-1.3 and I have an error 

`Unresolved dependency | openlayers (Missing). Farm Bee requires this module.`

I believe openlayers was phased out in this distribution.

**Comment by mstenta** [comment]
Ah good catch @botlfarm !

I think we just need to remove this line from the `farm_bee.info` file: https://github.com/farmOS/farm_bee/blob/7.x-1.x/farm_bee.info#L24

The module doesn't actually depend on OpenLayers directly, so it should be safe to remove that, and that should clear this up.  I should check other contrib modules to see if there are similar updates needed.

Do you feel comfortable making a pull request? Happy to give you the credit!

**Comment by mstenta** [comment]
Closed via https://github.com/farmOS/farm_bee/pull/3 - thanks @botlfarm !
